from datetime import datetime

HOST = ""
USER = "root"
PWD = ""

DATABASE_STIR = "STIR_DB"
TABLE_FF_DECOMP_VOLUME = "TABLE_FF_DECOMP_VOLUME"
TABLE_RESERVE_BALANCE = "TABLE_RESERVE_BALANCE"
TABLE_IORB = "TABLE_IORB"
TABLE_EFFR = "TABLE_EFFR"
TABLE_UPPER_BOUND = "TABLE_UPPER_BOUND"
TABLE_LOWER_BOUND = "TABLE_LOWER_BOUND"
TABLE_RRP_RATE = "TABLE_RRP_RATE"
TABLE_RRP_VOLUME = "TABLE_RRP_VOLUME"
TABLE_FOREIGN_RRP = "TABLE_FOREIGN_RRP"

FRED_API_KEY = ""

FRED_DATA_MAP = {
    TABLE_RESERVE_BALANCE: "WRESBAL",
    TABLE_IORB: "IORB",
    TABLE_EFFR: "EFFR",
    TABLE_UPPER_BOUND: "DFEDTARU",
    TABLE_LOWER_BOUND: "DFEDTARL",
    TABLE_RRP_RATE: "RRPONTSYAWARD",
    TABLE_RRP_VOLUME: "RRPONTSYD",
    TABLE_FOREIGN_RRP: "WLRRAFOIAL"
}

FRED_RT_START_DATE = datetime(2020, 1, 1)

TABLE_TGA_BALANCE = "TABLE_TGA_BALANCE"
TABLE_OVERDRAFT = "TABLE_OVERDRAFT"
TABLE_OFR_ON_DATA = "TABLE_OFR_ON_DATA"
TABLE_DAYLIGHT_OVERDFRAT = "TABLE_DAYLIGHT_OVERDFRAT"
TABLE_ELASTICITY = "TABLE_ELASTICITY"
TABLE_H8 = "TABLE_H8"

OFR_DATE_START_DATE = datetime(2018, 4, 2)

FRED_SERIES_NAME_MAP = {
        "effr": TABLE_EFFR,
        "rrp_volume": TABLE_RRP_VOLUME,
        "rrp_rate": TABLE_RRP_RATE,
        "foreign_rrp": TABLE_FOREIGN_RRP,
        "fed_reserve_balance": TABLE_RESERVE_BALANCE,
        "iorb": TABLE_IORB,
        "tga_balance": TABLE_TGA_BALANCE,
}

OFR_SERIES_NAME_MAP = {
        "sofr": "SOFRA",
        "bgcr": "BGCRA",
        "obfr": "OBFRA",
        "tgcr": "TGCRA",
        "effr": "EFFRA",

        "sofr_volume": "SOFR_UVA",
        "bgcr_volume": "BGCR_UVA",
        "obfr_volume": "OBFR_UVA",
        "tgcr_volume": "TGCR_UVA",
        "effr_volume": "EFFR_UVA",
}

# TYPE_BILL = "Bill"
# TYPE_BOND = "Bond"
# TYPE_NOTE = "Note"
# TYPE_CMB = "CMB"
# TYPE_TIPS_BOND = "TIPS Bond"
# TYPE_TIPS_NOTE = "TIPS Note"
# TYPE_FRN_NOTE = "FRN Note"

TREASURY_SEC_MAP = {
    "bill": "Bill",
    "cmb": "CMB",
    "frn": "FRN Note",
    "note": "Note",
    "bond": "Bond",
    "tips_note": "TIPS Note",
    "tips_bond": "TIPS Bond",
}

TREASURY_DATA_TYPE_REDEMPTION= "REDEMPTION_AMOUNT"
TREASURY_DATA_TYPE_OUTSTANDING = "OUTSTANDING_AMOUNT"
TREASURY_DATA_TYPE_OFFERING = "OFFERING_AMOUNT"
