from datetime import datetime

HOST = "34.148.149.200"
USER = "root"
PWD = "Ljs084719@@" #@@"

DATABASE_STIR = "STIR_DB"
TABLE_FF_DECOMP_VOLUME = "TABLE_FF_DECOMP_VOLUME"
TABLE_RESERVE_BALANCE = "TABLE_RESERVE_BALANCE"
TABLE_IORB = "TABLE_IORB"
TABLE_EFFR = "TABLE_EFFR"
TABLE_UPPER_BOUND = "TABLE_UPPER_BOUND"
TABLE_LOWER_BOUND = "TABLE_LOWER_BOUND"
TABLE_RRP_RATE = "TABLE_RRP_RATE"
TABLE_RRP_VOLUME = "TABLE_RRP_VOLUME"
TABLE_FOREIGN_RRP = "TABLE_FOREIGN_RRP"

FRED_API_KEY = '76c5b2251ca123fe274a24da976ca8ac'

FRED_DATA_MAP = {
    TABLE_RESERVE_BALANCE: "WRESBAL",
    TABLE_IORB: "IORB",
    TABLE_EFFR: "EFFR",
    TABLE_UPPER_BOUND: "DFEDTARU",
    TABLE_LOWER_BOUND: "DFEDTARL",
    TABLE_RRP_RATE: "RRPONTSYAWARD",
    TABLE_RRP_VOLUME: "RRPONTSYD",
    TABLE_FOREIGN_RRP: "WLRRAFOIAL"
}

FRED_RT_START_DATE = datetime(2020, 1, 1)

TABLE_TGA_BALANCE = "TABLE_TGA_BALANCE"
TABLE_OVERDRAFT = "TABLE_OVERDRAFT"
TABLE_OFR_ON_DATA = "TABLE_OFR_ON_DATA"
TABLE_DAYLIGHT_OVERDFRAT = "TABLE_DAYLIGHT_OVERDFRAT"
TABLE_ELASTICITY = "TABLE_ELASTICITY"

OFR_DATE_START_DATE = datetime(2018, 4, 2)